[package]
name = "touch-keybinds6n"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11 = "2.19.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8.24"
anyhow = "1.0.57"